export default [
  {
    name: "Default",
    value: {
      event:{
        logo:"",
        banner:"",
        primaryColor:"red",
        secondaryColor:"blue",
        fontColor:"white",
        name:"",
        location:"",
        startDate:"",
        endDate:"",
        supportEmail:"",
        supportPhone:"",
        otherInfo:""
      },
      sponsors:[
        "url","url","url"
      ],
      sessions:[
        {
          title:"",
          startDate:"",
          endDate:""
        },
        {
          title:"",
          startDate:"",
          endDate:""
        },
      ],
      speakers:[
        {
          thumbnail:"",
          name:"",
          lastName:""
        },
        {
          thumbnail:"",
          name:"",
          lastName:""
        },
        {
          thumbnail:"",
          name:"",
          lastName:""
        },
      ]

    },
  }, 
];
